apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rbdy10nqq-go 
  janus-idp.io/tekton: rbdy10nqq-go
  backstage.io/kubernetes-id: rbdy10nqq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rbdy10nqq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  